name: Publish
on:
  workflow_run:
    branches: 
      - main
    workflows: 
      - Tests
    types: 
      - completed
jobs:
  publish-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Build the Rust application
        run: cargo build --release
      
      - name: Bundle the front-end assets
        run: |
          npm install
          npm run build

      - name: Make package directories
        run: |
          mkdir -p ./package/www

      - name: Copy most important files to the package directory
        run: |
          cp ./target/release/deploy-experiment ./package/
          if [ -d "public" ]; then
            cp -a public package
          fi
          if [ -d "dist" ]; then
            cp -a dist package
          fi
          cp package-lock.json ./package/
          cp package.json ./package/
          cp ./www/root.html ./package/www/
          cp ./run.sh ./package/
          echo "console.log('run')" > ./package/main.ts

      - name: Setup Square Cloud
        uses: squarecloudofc/github-action@v2
        with:
          token: ${{ secrets.SQUARE_TOKEN }}
          install-only: true
        
      - name: Commit the application to the host
        run: |
          cd package
          squarecloud login --token=${{ secrets.SQUARE_TOKEN }}
          squarecloud commit ${{ secrets.SQUARE_APPLICATION_ID }}
          squarecloud app restart ${{ secrets.SQUARE_APPLICATION_ID }}
