name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish-production:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build and bundle the application
        run: |
          rustup update stable
          rustup default stable
          cargo build --release

      - name: Make package directories
        run: |
          mkdir -p ./package/www

      - name: Copy most important files to the package directory
        run: |
          cp ./target/release/deploy-experiment ./package/
          echo "copied executable"
          if [ -d "./public/" ]; then
            cp -a public package || true
          fi
          echo "copied public directory"
          cp ./package* ./package/
          echo "copied package files"
          cp ./www/root.html ./package/www/
          echo "copied html emplate"
          cp ./run.sh ./package/
          echo "copied sh"
          cp ./squarecloud.app ./package/
          echo "copied squarecloud"
          echo "console.log('run')" > ./package/main.ts
      
      - name: Move to package directory
        run: cd package

      - name: Setup Square Cloud
        uses: squarecloudofc/github-action@v2
        with:
          run: commit ${{ secrets.SQUARE_APPLICATION_ID }} --restart
          token: ${{ secrets.SQUARE_TOKEN }}
